"""TD & DoC generator — Word documents built from live platform data.

Technical Documentation follows the TD V1.5 template (cover T00, document control
T01, §1–§21, Appendix A/B), i.e. PPWR Annex VII Module A point 2 (a)–(f).
The EU declaration of conformity follows the Annex VIII model structure.

Scenario A — one TD + DoC per packaging unit, plus a document-package overview.
Scenario B — one consolidated TD (§2 lists every unit) + one DoC for all units.

Only approved / N/A items are stated as conclusions; anything still open is
printed as an OPEN ITEM so a draft can never be mistaken for a finished file.
"""
from __future__ import annotations

import datetime as dt
import io
import re
import zipfile
from pathlib import Path

from docx import Document as Docx
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Pt, RGBColor
from sqlalchemy.orm import Session

from . import ai_review, applicability, catalogue, config, workflow
from .db import Document, PackagingUnit, Project, now

BLUE = RGBColor(0x00, 0x3D, 0x7A)
GREY = RGBColor(0x5A, 0x6A, 0x7A)
RED = RGBColor(0xB9, 0x1C, 0x1C)

ANNEX_A = [
    ("00_Document_Control", [16]), ("01_Packaging_Identification", [1]),
    ("02_BOM_and_Material_Specifications", [2]), ("03_Design_and_Manufacturing", [3]),
    ("05_Article_5_Substances", [4]), ("06_Article_6_Recyclability", [5]),
    ("07_Article_7_Recycled_Content", [6]), ("08_Article_8_Biobased", [7]),
    ("09_Article_9_Compostability", [8]), ("10_Article_10_Minimisation", [9]),
    ("11_Article_11_Reusability", [10]), ("12_Article_12_Labelling", [11]),
    ("13_Risk_and_Change", [12]), ("14_Manufacturing_Control", [13]),
    ("15_Standards_and_Evidence_Register", [14]), ("17_Supplier_Evidence", [15]),
]
FOLDER_FOR_CAT = {c: f for f, cats in ANNEX_A for c in cats}


# ---------------------------------------------------------------------------
# docx helpers
# ---------------------------------------------------------------------------

def _new_doc() -> Docx:
    doc = Docx()
    st = doc.styles["Normal"]
    st.font.name = "Calibri"
    st.font.size = Pt(10)
    for name, size in (("Heading 1", 14), ("Heading 2", 12), ("Heading 3", 10.5)):
        h = doc.styles[name]
        h.font.color.rgb = BLUE
        h.font.size = Pt(size)
        h.font.name = "Calibri"
    return doc


def _shade(cell, hex_fill: str) -> None:
    tcpr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_fill)
    tcpr.append(shd)


def _table(doc, headers: list[str], rows: list[list], widths: list[float] | None = None):
    t = doc.add_table(rows=1, cols=len(headers))
    t.style = "Table Grid"
    t.alignment = WD_TABLE_ALIGNMENT.CENTER
    for i, h in enumerate(headers):
        c = t.rows[0].cells[i]
        c.text = ""
        r = c.paragraphs[0].add_run(h)
        r.bold, r.font.size, r.font.color.rgb = True, Pt(8.5), RGBColor(0xFF, 0xFF, 0xFF)
        _shade(c, "003D7A")
    for row in rows:
        cells = t.add_row().cells
        for i, v in enumerate(row):
            cells[i].text = ""
            run = cells[i].paragraphs[0].add_run("" if v is None else str(v))
            run.font.size = Pt(8.5)
            if isinstance(v, str) and v.startswith("OPEN"):
                run.font.color.rgb, run.bold = RED, True
    doc.add_paragraph()
    return t


def _kv(doc, pairs: list[tuple[str, str]]):
    t = doc.add_table(rows=0, cols=2)
    t.style = "Table Grid"
    for k, v in pairs:
        cells = t.add_row().cells
        cells[0].text = ""
        r = cells[0].paragraphs[0].add_run(k)
        r.bold, r.font.size = True, Pt(9)
        _shade(cells[0], "EEF3FA")
        cells[1].text = ""
        run = cells[1].paragraphs[0].add_run(v or "—")
        run.font.size = Pt(9)
        if (v or "").startswith("OPEN"):
            run.font.color.rgb, run.bold = RED, True
    doc.add_paragraph()


def _para(doc, text: str, italic=False, color=None, size=None, bold=False):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.italic, r.bold = italic, bold
    if color is not None:
        r.font.color.rgb = color
    if size:
        r.font.size = Pt(size)
    return p


def _header_footer(doc, left: str, status: str) -> None:
    sec = doc.sections[0]
    hp = sec.header.paragraphs[0]
    hp.text = ""
    r = hp.add_run(f"{left}    ·    {status}")
    r.font.size, r.font.color.rgb = Pt(8), (RED if status.startswith("DRAFT") else GREY)
    fp = sec.footer.paragraphs[0]
    fp.text = ""
    r = fp.add_run(f"Generated by the {config.APP_NAME} ({config.APP_SUB}) on {now():%d %b %Y %H:%M}. "
                   "PPWR (EU) 2025/40 Annex VII Module A.")
    r.font.size, r.font.color.rgb = Pt(7.5), GREY


# ---------------------------------------------------------------------------
# data access
# ---------------------------------------------------------------------------

class Scope:
    """What one TD covers: a single unit (scenario A) or all units (scenario B)."""

    def __init__(self, project: Project, unit: PackagingUnit | None):
        self.project, self.unit = project, unit
        self.units = [unit] if unit else list(project.units)
        ids = {u.id for u in self.units}
        self.subs = [s for s in project.submissions if s.unit_id in ids or s.unit_id is None]
        self.evidence = [e for e in project.evidence if e.unit_id in ids or e.unit_id is None]
        self.components = [c for u in self.units for c in u.components]
        self.matrix = applicability.matrix(project)

    def sub(self, item_id: str, unit: PackagingUnit | None = None) -> list:
        return [s for s in self.subs if s.item_id == item_id and (unit is None or s.unit_id in (unit.id, None))]

    def field(self, item_id: str, key: str) -> str:
        for s in self.sub(item_id):
            if s.data.get(key):
                return str(s.data[key])
        return ""

    def done(self, item_id: str) -> bool:
        subs = self.sub(item_id)
        return bool(subs) and all(s.is_done for s in subs)

    def ev_for(self, item_ids: list[str]) -> list:
        return [e for e in self.evidence if e.item_id in item_ids]

    @property
    def readiness(self) -> float:
        return workflow.readiness(self.subs)


def _state(s) -> str:
    if s.status == "approved":
        return "Approved" + (f" — {s.reviewed_by}" if s.reviewed_by else "")
    if s.status == "na":
        return "N/A — " + (s.na_reason or "rationale recorded")
    return f"OPEN — {catalogue.STATUS_LABEL[s.status]}"


def _unit_label(s, scope: Scope) -> str:
    if s.unit_id is None:
        return "all units"
    u = next((u for u in scope.units if u.id == s.unit_id), None)
    return u.code if u else ""


def td_number(project: Project, unit: PackagingUnit | None) -> str:
    return f"TD-{project.code}-{unit.code if unit else project.ps_code}"


def doc_number(project: Project, unit: PackagingUnit | None) -> str:
    base = ""
    for s in project.submissions:
        if s.item_id == "C16-66" and s.data.get("docNo"):
            base = s.data["docNo"]
    base = base or f"DoC-{dt.date.today():%Y}-{project.code}"
    return f"{base}-{unit.code}" if unit else base


def _version(session: Session, project: Project, unit, kind: str) -> int:
    q = session.query(Document).filter(Document.project_id == project.id, Document.kind == kind,
                                       Document.unit_id == (unit.id if unit else None))
    return (max((d.version for d in q), default=0)) + 1


# ---------------------------------------------------------------------------
# Technical documentation
# ---------------------------------------------------------------------------

def _item_block(doc, scope: Scope, item_ids: list[str]) -> None:
    rows = []
    for iid in item_ids:
        it = catalogue.item(iid)
        for s in scope.sub(iid):
            vals = "; ".join(f"{f['label']}: {s.data.get(f['k'])}" for f in it.get("fields", [])
                             if s.data.get(f["k"]))
            ev = ", ".join(e.code for e in scope.evidence if e.item_id == iid and e.unit_id in (s.unit_id, None))
            rows.append([iid, it["name"], _unit_label(s, scope), vals or "—", ev or "—", _state(s)])
    if rows:
        _table(doc, ["Item", "Requirement", "Unit", "Content", "Evidence", "Status"], rows)


def build_td(scope: Scope, number: str, version: int, status: str) -> Docx:
    p, doc = scope.project, _new_doc()
    _header_footer(doc, f"{number} v{version}", status)
    title = doc.add_heading("Technical Documentation", 0)
    title.runs[0].font.color.rgb = BLUE
    _para(doc, "Regulation (EU) 2025/40 on packaging and packaging waste (PPWR) — Annex VII, "
               "Module A internal production control, point 2", italic=True, color=GREY)
    if status.startswith("DRAFT"):
        _para(doc, f"DRAFT — readiness {scope.readiness:.0%}. Open items are marked OPEN and must be closed "
                   "before this documentation supports an EU declaration of conformity.", bold=True, color=RED)

    doc.add_heading("T00 Cover information", 1)
    _kv(doc, [
        ("TD number / version", f"{number} / v{version}"),
        ("Date", f"{dt.date.today():%d %B %Y}"),
        ("Manufacturer", p.client.name),
        ("Registered address", p.client.address),
        ("EU authorised representative", p.client.eu_representative or "Not applicable"),
        ("Packaged product", p.title),
        ("Packaging system", p.ps_code),
        ("Packaging units covered", ", ".join(f"{u.code} {u.name} (UPI {u.upi or 'OPEN'})" for u in scope.units)),
        ("Technical-file scenario", "A — per-unit technical file (document package)" if p.scenario == "A"
         else "B — consolidated technical file (producer = packaging manufacturer)"),
        ("Retention", "10 years (reusable packaging)" if p.reusable else "5 years after placing on the market (single-use)"),
    ])

    doc.add_heading("T01 Document control", 1)
    _kv(doc, [("Prepared by", scope.field("C16-69", "prep") or "OPEN"),
              ("Reviewed by", scope.field("C16-69", "rev") or "OPEN"),
              ("Approved by", scope.field("C16-69", "appr") or "OPEN"),
              ("Independent review", "TÜV SÜD expert review on the PPWR Digital Platform (item-level audit trail)")])

    doc.add_heading("1 Purpose, scope and regulatory basis", 1)
    doc.add_paragraph(
        f"This technical documentation demonstrates the conformity of the packaging described in section 2 with "
        f"the requirements of Articles 5 to 12 of Regulation (EU) 2025/40 that apply to it, following the "
        f"conformity assessment procedure of Article 38 and Annex VII (Module A). It contains the elements of "
        f"Annex VII point 2 (a)–(f): general description and intended use (§2), design, drawings and component "
        f"materials (§3–§4), standards applied (§16), the qualitative description of the Article 6, 10 and 11 "
        f"assessments (§7, §11, §12), test reports (§17) and an analysis of the risks of non-conformity (§14).")

    doc.add_heading("2 Packaging identification and intended use", 1)
    _table(doc, ["Unit", "UPI", "Name", "Level", "Type", "SKUs", "Mass (g)", "Dimensions (mm)", "Supplier / site"],
           [[u.code, u.upi or "OPEN", u.name, u.level, u.pack_type, u.skus,
             f"{u.mass_g:g}" if u.mass_g else "OPEN", u.dims,
             ", ".join(x for x in (u.supplier_name, u.site, u.country) if x)] for u in scope.units])
    if p.product_description:
        doc.add_paragraph(p.product_description)

    doc.add_heading("3 Packaging structure and BOM", 1)
    _table(doc, ["Component", "Type", "Description", "Structure", "Material", "Mass (g)", "Supplier · trace code", "PCR %"],
           [[c.code, c.pack_type, c.description, c.structure, c.material,
             f"{c.mass_g:g}" if c.mass_g else "OPEN",
             " · ".join(x for x in ((c.supplier.name if c.supplier else ""),
                                    (c.supplier_material.trace_code if c.supplier_material else "")) if x) or "—",
             f"{c.recycled_pct:g}" if c.recycled_pct is not None else "—"] for c in scope.components])
    _item_block(doc, scope, ["C02-07", "C02-08", "C02-09"])

    doc.add_heading("4 Design and manufacturing documentation", 1)
    _item_block(doc, scope, ["C03-10", "C03-11", "C03-12", "C03-13", "C03-14", "C03-15"])

    doc.add_heading("5 PPWR applicability and compliance matrix", 1)
    _table(doc, ["Requirement", "Applicability", "Applies from", "Basis / rationale", "Evidence"],
           [[r.article, r.status, r.applies_from, r.basis, r.evidence] for r in scope.matrix])

    art_sections = [
        ("6 Article 5 — Substances of concern", ["C04-16", "C04-17", "C04-18"]),
        ("7 Article 6 — Recyclability / design for recycling", ["C05-19", "C05-20", "C05-21"]),
        ("8 Article 7 — Recycled content", ["C06-22", "C06-23"]),
        ("9 Article 8 — Biobased feedstock", ["C07-24", "C07-25"]),
        ("10 Article 9 — Compostability", ["C08-26", "C08-27", "C08-28"]),
        ("11 Article 10 — Packaging minimisation", ["C09-29", "C09-30", "C09-31", "C09-32", "C09-33",
                                                    "C09-34", "C09-35", "C09-36"]),
        ("12 Article 11 — Reusability", ["C10-37", "C10-38", "C10-39"]),
        ("13 Article 12 — Labelling", ["C11-40", "C11-41", "C11-42", "C11-43", "C11-44", "C11-45"]),
    ]
    for heading, ids in art_sections:
        doc.add_heading(heading, 1)
        if heading.startswith("6 "):
            rows = []
            for c in scope.components:
                certs = [x for x in (c.supplier_material.certificates if c.supplier_material else [])
                         if x.doc_type == "hm" and x.status == "valid"]
                cert = certs[0] if certs else None
                rows.append([c.code, c.material, cert.number if cert else "—", cert.value if cert else "—",
                             f"{cert.expires:%d %b %Y}" if cert and cert.expires else "—",
                             "≤ 100 mg/kg ✓" if cert and (ai_review._number(cert.value) or 0) <= 100 else
                             ("OPEN — no supplier certificate" if not cert else "EXCEEDS LIMIT")])
            _para(doc, "Heavy metals per component (Art 5(4): Pb + Cd + Hg + Cr(VI) ≤ 100 mg/kg):", bold=True)
            _table(doc, ["Component", "Material", "Report", "Result", "Valid until", "Assessment"], rows)
        _item_block(doc, scope, ids)

    doc.add_heading("14 Risk analysis and assessment of non-conformity", 1)
    risk_rows = []
    for r in scope.matrix:
        if r.status == applicability.NA:
            continue
        open_items = [s for s in scope.subs if catalogue.item(s.item_id)["article"] == r.key and not s.is_done]
        risk_rows.append([r.article, "Low" if not open_items else "Open",
                          r.evidence, "Controlled by approved evidence" if not open_items
                          else f"OPEN — {len(open_items)} item(s) not yet approved"])
    _table(doc, ["Requirement", "Residual risk", "Control / evidence", "Status"], risk_rows)
    _item_block(doc, scope, ["C12-46"])

    doc.add_heading("15 Manufacturing control and change management", 1)
    doc.add_paragraph("Series production remains in conformity through incoming inspection, production "
                      "control and final release (Annex VII point 3; Art 15(4)). Supplier and material changes are "
                      "traced by the platform's change-impact engine, which re-opens affected evidence and flags "
                      "this documentation for update.")
    _item_block(doc, scope, ["C12-47", "C12-48", "C12-49", "C12-50", "C13-51", "C13-52", "C13-53"])

    doc.add_heading("16 Standards and technical specifications", 1)
    std = next((s for s in scope.sub("C14-54")), None)
    rows = [r for r in (std.table if std else []) if r and str(r[0]).strip()]
    _table(doc, ["Standard / specification", "Edition", "Clause", "Requirement covered", "Evidence"],
           rows or [["OPEN — no standards listed", "", "", "", ""]])

    doc.add_heading("17 Evidence register", 1)
    _table(doc, ["Evidence ID", "Title", "Type", "Document no.", "Issuer", "Issued", "Conformity"],
           [[e.code, e.title, catalogue.EVIDENCE_TYPES.get(e.type_code, e.type_code), e.file_no, e.issuer,
             f"{e.issued_date:%d %b %Y}" if e.issued_date else "", e.conformity] for e in scope.evidence]
           or [["OPEN — no evidence uploaded", "", "", "", "", "", ""]])

    doc.add_heading("18 Supplier evidence checklist", 1)
    rows = []
    for c in scope.components:
        m = c.supplier_material
        certs = ", ".join(f"{catalogue.CERT_SHORT[x.doc_type]} {x.number}"
                          + (f" (to {x.expires:%m/%Y})" if x.expires else "")
                          for x in (m.certificates if m else []) if x.status == "valid")
        rows.append([c.code, c.supplier.name if c.supplier else "—", m.code if m else "—",
                     m.trace_code if m else "—", certs or "OPEN — no supplier certificates"])
    _table(doc, ["Component", "Supplier", "Material", "Trace code", "Valid certificates"], rows)
    _item_block(doc, scope, ["C15-56", "C15-57", "C15-58", "C15-59", "C15-60", "C15-61", "C15-62",
                             "C15-63", "C15-64", "C15-65"])

    doc.add_heading("19 Conformity assessment conclusion", 1)
    open_subs = [s for s in scope.subs if not s.is_done]
    if not open_subs:
        doc.add_paragraph("All applicable requirements of Articles 5 to 12 have been assessed and are supported by "
                          "approved evidence. Items not applicable are recorded with their rationale in §5. "
                          "Conformity of the packaging is demonstrated; the EU declaration of conformity may be "
                          "drawn up (Art 39).")
    else:
        _para(doc, f"OPEN — {len(open_subs)} item(s) are not yet approved. Conformity is not yet demonstrated.",
              bold=True, color=RED)
        _table(doc, ["Item", "Requirement", "Unit", "Status"],
               [[s.item_id, catalogue.item(s.item_id)["name"], _unit_label(s, scope),
                 catalogue.STATUS_LABEL[s.status]] for s in open_subs[:60]])

    doc.add_heading("20 EU declaration of conformity — cross-reference", 1)
    _kv(doc, [("EU DoC number", doc_number(p, scope.unit if p.scenario == "A" else None)),
              ("Signatory", scope.field("C16-66", "sign") or "OPEN"),
              ("Place of issue", scope.field("C16-66", "place") or "OPEN")])

    doc.add_heading("21 Approval", 1)
    _kv(doc, [("Prepared", scope.field("C16-69", "prep") or "OPEN"),
              ("Reviewed", scope.field("C16-69", "rev") or "OPEN"),
              ("Approved", scope.field("C16-69", "appr") or "OPEN")])

    doc.add_heading("Appendix A — Evidence file structure", 1)
    _table(doc, ["Folder", "Content"],
           [[f, ", ".join(catalogue.category(c)["name"] for c in cats)] for f, cats in ANNEX_A])
    doc.add_heading("Appendix B — Legal references", 1)
    for ref in ("Regulation (EU) 2025/40 (PPWR), OJ L, 22.1.2025 — Art 5–12, 15, 38, 39, Annex II, IV, VII, VIII",
                "Commission Guidance C(2026) 2151 and PPWR FAQ (2026)",
                "EN 13427–EN 13432 (harmonised standards under Directive 94/62/EC, transitional use)",
                "Regulation (EC) 1935/2004 (food-contact materials), where applicable"):
        doc.add_paragraph(ref, style="List Bullet")
    return doc


# ---------------------------------------------------------------------------
# EU declaration of conformity — Annex VIII
# ---------------------------------------------------------------------------

def build_doc(scope: Scope, number: str, version: int, status: str, td_no: str) -> Docx:
    p, doc = scope.project, _new_doc()
    _header_footer(doc, f"{number} rev {version:02d}", status)
    h = doc.add_heading(f"EU declaration of conformity No {number}", 0)
    h.runs[0].font.color.rgb = BLUE
    _para(doc, "Regulation (EU) 2025/40 — Article 39, Annex VIII model structure", italic=True, color=GREY)
    if status.startswith("DRAFT"):
        _para(doc, "DRAFT — not for signature. The technical documentation still has open items.",
              bold=True, color=RED)
    upis = "; ".join(f"{u.upi or 'OPEN'} ({u.code} {u.name})" for u in scope.units)
    points = [
        ("1. No (unique identification of the packaging)", upis),
        ("2. Name and address of the manufacturer / authorised representative",
         f"{p.client.name}, {p.client.address}" + (f" — authorised representative: {p.client.eu_representative}"
                                                   if p.client.eu_representative else "")),
        ("3.", "This declaration of conformity is issued under the sole responsibility of the manufacturer."),
        ("4. Object of the declaration",
         f"{p.title} — packaging system {p.ps_code}: " + "; ".join(
             f"{u.name}, {u.level.lower()} packaging, {u.pack_type or 'packaging'}, "
             f"{', '.join(sorted({c.material for c in u.components if c.material}))}, SKUs {u.skus or '—'}"
             for u in scope.units)),
        ("5. Conformity with Union harmonisation legislation",
         "The object of the declaration described in point 4 is in conformity with Regulation (EU) 2025/40 "
         "(Articles 5 to 12 as applicable — see technical documentation §5)."
         + (" Regulation (EC) No 1935/2004 (food-contact materials)." if p.food_contact else "")),
        ("6. Harmonised standards / common specifications / other technical specifications",
         "; ".join(r[0] for r in (scope.sub("C14-54")[0].table if scope.sub("C14-54") else []) if r and r[0])
         or "OPEN"),
        ("7. Notified body", "Not applicable — Module A internal production control (Annex VII)."),
        ("8. Additional information",
         f"Technical documentation {td_no}. Retention: "
         + ("10 years (reusable)." if p.reusable else "5 years after placing on the market (single-use).")),
    ]
    _kv(doc, points)
    doc.add_heading("Packaging composition", 2)
    _table(doc, ["Unit", "Component", "Material", "Mass (g)", "Recycled content"],
           [[c.unit.code, c.description or c.pack_type, c.material, f"{c.mass_g:g}" if c.mass_g else "",
             f"{c.recycled_pct:g} %" if c.recycled_pct is not None else "—"] for c in scope.components])
    doc.add_heading("Signed for and on behalf of", 2)
    _kv(doc, [("Manufacturer", p.client.name),
              ("Place and date of issue", f"{scope.field('C16-66', 'place') or 'OPEN'}, {dt.date.today():%d %B %Y}"),
              ("Name, function", scope.field("C16-66", "sign") or "OPEN"),
              ("Signature", "")])
    return doc


def build_package(project: Project, entries: list[tuple[str, str, str]], status: str) -> Docx:
    doc = _new_doc()
    _header_footer(doc, f"Document package {project.code}", status)
    h = doc.add_heading("PPWR document package", 0)
    h.runs[0].font.color.rgb = BLUE
    _para(doc, f"{project.client.name} — {project.title} — packaging system {project.ps_code}", color=GREY)
    doc.add_paragraph("Scenario A: each packaging unit has its own technical documentation and EU declaration of "
                      "conformity. This overview indexes the files handed to the final packaging user.")
    _table(doc, ["Unit", "Technical documentation", "EU declaration of conformity"],
           [[u, td, dc] for u, td, dc in entries])
    return doc


# ---------------------------------------------------------------------------
# entry points
# ---------------------------------------------------------------------------

def _save(doc: Docx, project: Project, name: str) -> Path:
    folder = config.GENERATED_DIR / project.code
    folder.mkdir(parents=True, exist_ok=True)
    path = folder / name
    doc.save(path)
    return path


def generate(session: Session, project: Project, actor: str, trigger: str = "manual") -> list[Document]:
    """Generate the TD/DoC set for the project's scenario. Earlier drafts are superseded."""
    for d in project.documents:
        if d.status == "draft":
            d.status = "superseded"
    made: list[Document] = []
    scopes = [Scope(project, u) for u in project.units] if project.scenario == "A" else [Scope(project, None)]
    entries = []
    for sc in scopes:
        ready = sc.readiness
        status = "ISSUE CANDIDATE" if ready >= 1 else f"DRAFT — {ready:.0%} ready"
        td_no, dc_no = td_number(project, sc.unit), doc_number(project, sc.unit)
        v_td, v_dc = _version(session, project, sc.unit, "TD"), _version(session, project, sc.unit, "DOC")
        stamp = f"{now():%Y%m%d-%H%M%S}"
        td_path = _save(build_td(sc, td_no, v_td, status), project, f"{td_no}_v{v_td}_{stamp}.docx")
        dc_path = _save(build_doc(sc, dc_no, v_dc, status, f"{td_no} v{v_td}"), project,
                        f"{_safe(dc_no)}_rev{v_dc:02d}_{stamp}.docx")
        for kind, number, version, path in (("TD", td_no, v_td, td_path), ("DOC", dc_no, v_dc, dc_path)):
            d = Document(project=project, unit_id=sc.unit.id if sc.unit else None, kind=kind, number=number,
                         version=version, status="draft", path=str(path), readiness=ready, trigger=trigger,
                         generated_by=actor)
            session.add(d)
            made.append(d)
        entries.append((sc.unit.code if sc.unit else "all", f"{td_no} v{v_td}", f"{dc_no} rev {v_dc:02d}"))
    if project.scenario == "A":
        v = _version(session, project, None, "PACKAGE")
        overall = workflow.readiness(project.submissions)
        path = _save(build_package(project, entries, "ISSUE CANDIDATE" if overall >= 1 else "DRAFT"),
                     project, f"PKG-{project.code}_v{v}_{now():%Y%m%d-%H%M%S}.docx")
        d = Document(project=project, unit_id=None, kind="PACKAGE", number=f"PKG-{project.code}", version=v,
                     status="draft", path=str(path), readiness=overall, trigger=trigger, generated_by=actor)
        session.add(d)
        made.append(d)
    return made


def _safe(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", s)


def dossier_zip(project: Project, documents: list[Document]) -> bytes:
    """Authority-request dossier (Art 15(10): within 10 days) — TD, DoC and every
    evidence file, filed in the Appendix A folder structure."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for d in documents:
            if Path(d.path).exists():
                z.write(d.path, f"{project.code}/00_Document_Control/{Path(d.path).name}")
        for e in project.evidence:
            if not e.stored_path or not Path(e.stored_path).exists():
                continue
            it = catalogue.item(e.item_id) if e.item_id else None
            folder = FOLDER_FOR_CAT.get(it["cat"], "15_Standards_and_Evidence_Register") if it else "17_Supplier_Evidence"
            if e.type_code == "TST":
                folder = "16_Test_Reports"
            z.write(e.stored_path, f"{project.code}/{folder}/{e.code}__{_safe(e.filename or 'file')}")
        z.writestr(f"{project.code}/README.txt",
                   f"PPWR dossier for {project.title} ({project.client.name}).\n"
                   f"Prepared {now():%d %b %Y %H:%M} on the {config.APP_NAME}.\n"
                   "Structure follows Appendix A of the technical documentation.\n")
    return buf.getvalue()
